log_format  read  '$time_iso8601 $remote_addr "$request" $status "$http_user_agent"';

server {
    listen 80 default_server;
    root /usr/share/nginx/html;
    index index.html;
    access_log /var/log/nginx/read.log read;
}
