log_format  read  '$msec $status "$uri" $remote_addr "$request" "$http_user_agent"';

server {
    listen 80 default_server;
    root /usr/share/nginx/html;
    index index.html;
    access_log /var/log/nginx/read.log read;
}
