# Generated by Django 6.1.1 on 2026-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_scoresnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pattern',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
