# Generated by Django 6.1.1 on 2026-09-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_case_pattern_case_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='dest_host',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='detection',
            name='src_host',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
