# Generated by Django 6.1.1 on 2026-09-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_detection_dest_host_detection_src_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='read_of',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='truncated',
            field=models.BooleanField(default=False),
        ),
    ]
