# Generated by Django 6.1.1 on 2026-09-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_session_read_of_session_truncated'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='earliest',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='latest',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
